sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: XTSmnomcHXY//Wfj/xDmX2q0ZjobJllvh31Yf27rC722Rm7jijO7uBCkCkhtn2oRjKozMHZ6Q/SFO2jxN8UmWzX8zxfzwxsEaAD9NrwacgwcN5YIQGlW9zweiEaNF6jL/zEGeawdV9ZRz9eOhdKLmoxDN2J4LRW7In8cJ8d/ZPaUm1sZGGYydOKduFQUixTQk4lXs1/tOgjaVVxWYAqLu8Qljo8RzgACGgrWkW4rnmxqKO2/pFSSIRYBrwDTzsSgGq10CDBwDeHjK87IS+4SzSX8nfd7L/99F876VWiwtxaQN5DaNjKUQAymDYoeRvkGavQZIIT92cgV4sXW5MNVVop371K7XoAWH62N7EOPmwtmsfSFpxmLqFD8FzklaSfNCxrVsMcrTyLx4fSUwSqMZgq1WAiklU0nl20oyjUO6hOh5b+UaG+feu+btry0t9K3/35J4cwTbWNJaOQ2PLruS8hAUVXC/iZnEPbk3luPs0tQn6IIy1DGcYuvRiYomg0POhvIB5qzunmMGlJx4anaDmYKxVwAdGM0GZzasSjzMct46Un+e1o19wUpPyw8yKHCu62LnduchPLbBUjRnOxRxhrNcwdydtHQPQqfRZX0XHqHcgO2CbpDfd/kBMjjE2g+AN83YpGhD7AJFs4rydG/245JSWVIxdNhgSAzbHF+Ixc=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Sara-Crewe--Or-What-Happened-at-Miss-Minchin-s-Boarding-School_137
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy